"use client"
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Provider } from 'react-redux'
import { store } from "@/store/store";
import SideNavbar from "@/components/sideNavbar";
import { cn } from "@/lib/utils";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen w-full bg-white text-black flex ",
          inter.className,
          {
            "debug-screens": process.env.NODE_ENV === "development"
          }
        )}
      >
        {/* sidebar */}
        {/* <p className="border">Sidebar</p> */}
        <Provider store={store}>
        <SideNavbar  />
        {/* main page */}
        <div className="p-8 w-full">{children}</div>

        </Provider>
      </body>
    </html>
  );
}
